# -*- coding: utf-8 -*-
"""Projeto Calculadora Inteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dwy4dKEdh_QlwfxpY5E9KqIXSjhyQVoK
"""



"""***Esse é um projeto que mostra como se fazer uma calculadora inteligente usando o Python.***

*Faça contas usando a Calculadora Inteligente e descubra a senha para liberar uma mensagem secreta!*

**Aviso: A calculadora Inteligente não aceita resultados acima de 10.000 e nem divisões por 0.**

**Calculadora Inteligente!**
"""

# calculadoraint()
print("Calculadora Inteligente")
print("Calcule e Descubra a Senha Secreta")
print("Bem vindo usuário, qual o seu nome?")
nome = input() # Essa é a variável
print("Ah, sim você é o", nome, "você consegue descobrir a mensagem secreta sozinho ou precisa de uma dica?") # Coloca o nome do usuário
resposta= input("(Descobrir sozinho/Preciso de dica): ")
if resposta.lower() == "preciso de dica":
    print("A dica é: 10*2+20/2+15-5+10")
elif resposta.lower() == "descobrir sozinho":
    print("Boa sorte!")

while True:
    primeiro_input = input("Digite o Primeiro Número ou digite Sair para fechar a calculadora:  ")
    if primeiro_input.lower() == "sair":
        print("Obrigado por usar a Calculadora Inteligente!")
        break # Sair do Loop

    try:
        num1 = float(primeiro_input)
    except ValueError:
        print("Entrada inválida para o primeiro número. Por favor, digite um número ou 'Sair'.")
        continue # Volta para o início do loop

    operaçao = input("Qual operação deseja realizar?(+, -, *, /): ")
    segundo_input = input("Digite o Segundo Número:  ")

    try:
        num2 = float(segundo_input)
    except ValueError:
        print("Entrada inválida para o segundo número. Por favor, digite um número.")
        continue # Volta para o início do loop

    if operaçao == '+':
      """Adição"""
      resultado = num1 + num2
    elif operaçao == '-':
      """Subtração"""
      resultado = num1 - num2
    elif operaçao == '*':
      """Multiplicação"""
      resultado = num1 * num2
    elif operaçao == '/':
       """Divisão"""
       if num2 == 0:
          print("Operação não permitida!")
          continue # Volta para o início do Loop
       else:
          resultado = num1 / num2
    else:
        print("Operação inválida!")
        continue # Volta para o início do Loop

    if resultado > 10000:
      print("Erro, essa calculadora só pode calcular até 10.000")
    else:
      print(f"Resultado: {resultado}")

      if resultado == 50:
          print("Senha Correta")
          print("Mensagem Secreta: Muitos jogos usam o Sistema de Python para programar! Um deles é o Rpg Maker e os jogos de celular!")

    reset_calculo = input("Calcular novamente? (sim/não): ")
    if reset_calculo.lower() == "não":
        print("Obrigado por usar a Calculadora Inteligente!")
        break # Sair do Loop